### ISSUE TITLE
Folder compare shows sql files different, however ignore blank lines option is checked

### ISSUE THREAD

**Issue by urbantamas** [datadiode/winmerge2011#15]
I'm using 2011.211.117, and folder compare shows difference for large number of files, because on left side the last line of the file contains a single "/" character, and on the right side the same file contains an extra new line after the "/" character.

Winmerge options are the follows: 
whitespace ignore all, 
Ignore blank lines ON
Ignore case OFF
Ignore carriage return ON

The same compare in Winmerge.2011.009.217 works fine, there is no difference using the same options above.

![winmerge 2011 foldercompare sqlfiles](https://user-images.githubusercontent.com/47850488/111195128-38e7e700-85bc-11eb-968a-02cad029087a.jpg)

**Comment by datadiode** [comment]
I think the old behavior was incorrect, because none of the options technically targets the lack of EOL at the end of one file.  
How does 2011.009.217 behave with Ignore carriage return differences OFF?  
With both files having Windows line endings, this should not make a difference, but I suspect with 2011.009.217 it does.

**Comment by datadiode** [comment]
Related to https://github.com/datadiode/winmerge2011/commit/e604adf  
It seems the current behavior is like in WinMerge 2.16 (which uses older DiffUtils sources).  
Simply reverting above commit creates effects.  
Detecting the situation in DiffUtils::diffutils_compare_files(), after running diff algorithm, could be an option.

**Comment by urbantamas** [comment]
thanks, it works perfectly! there is no diff in the last line.
