### ISSUE TITLE
Winmerge 2011 v381/486 Crash Dumps 

### ISSUE THREAD

**Issue by click-click** [datadiode/winmerge2011#6]
I've been using 2011.9.217 for sometime now without problems. I decided to try the new versions
and found that they crash when pocessing certain directories. I have included dumps for both.
[WinMergeU.exe.v466.zip](https://github.com/datadiode/winmerge2011/files/5562341/WinMergeU.exe.v466.zip)
[WinMergeU.exe.v381.zip](https://github.com/datadiode/winmerge2011/files/5562309/WinMergeU.exe.v381.zip)

Problem signature:
  Problem Event Name:	BEX64
  Application Name:	WinMergeU.exe
  Application Version:	0.2011.210.466
  Application Timestamp:	5fae43d6
  Fault Module Name:	WinMergeU.exe
  Fault Module Version:	0.2011.210.466
  Fault Module Timestamp:	5fae43d6
  Exception Offset:	00000000000e5d86
  Exception Code:	c0000409
  Exception Data:	0000000000000000
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	e70c
  Additional Information 2:	e70c80ad8e7bc5ebf59198e5b1e942fd
  Additional Information 3:	af78
  Additional Information 4:	af7821175157bb27a01513089f8f4f7c

**Comment by datadiode** [comment]
Thanks for bug report.
Can you try to reproduce the crash with a Debug build from [here](https://ci.appveyor.com/project/datadiode/winmerge2011/builds/36437260/artifacts)?

**Comment by click-click** [comment]
[WinMergeU.exeDebug.zip](https://github.com/datadiode/winmerge2011/files/5577389/WinMergeU.exeDebug.zip)

**Comment by datadiode** [comment]
Does [this](https://ci.appveyor.com/project/datadiode/winmerge2011/builds/36438663/artifacts) build fix the issue?

**Comment by click-click** [comment]
Hold on ... will try in a minute...

**Comment by click-click** [comment]
That fixed it! I ran two tests where I had problems. One big compare and the other small. I'll let you know if I notice anything else. Thanks for taking the time to look at this. Hopefully portableapps.com will update the 2011 version sometime soon. The original Winmerge was updated there recently, but I've gotten used to 2011.
